import React, { useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { 
  Video, 
  FileText, 
  Image as ImageIcon, 
  Sparkles, 
  Download, 
  Copy, 
  Check, 
  X, 
  ShieldCheck, 
  Radio, 
  QrCode, 
  Share2, 
  Lock,
  Camera,
  Play
} from 'lucide-react';
import { UFOSighting, AnomalyDeepDiveExplanation } from '../types';

interface CreatorExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  sighting?: UFOSighting | null;
  deepDive?: AnomalyDeepDiveExplanation | null;
  userClearance: string;
  onNeedUpgrade: () => void;
}

export const CreatorExportModal: React.FC<CreatorExportModalProps> = ({
  isOpen,
  onClose,
  sighting,
  deepDive,
  userClearance,
  onNeedUpgrade
}) => {
  const isCreatorOrAnalyst = userClearance === 'ANALYST';

  const [copiedScript, setCopiedScript] = useState(false);
  const [copiedMd, setCopiedMd] = useState(false);
  const [exportingPdf, setExportingPdf] = useState(false);
  const [exportingPng, setExportingPng] = useState(false);

  if (!isOpen) return null;

  const incidentTitle = sighting?.title || deepDive?.title || 'Nevada Test Range Uncorrelated Aerospace Anomaly';
  const incidentDate = sighting?.date || new Date().toLocaleDateString();
  const lat = sighting?.latitude || sighting?.coordinates?.lat || 0;
  const lng = sighting?.longitude || sighting?.coordinates?.lng || 0;
  const location = sighting ? `${lat.toFixed(4)}°, ${lng.toFixed(4)}° (${sighting.locationName || sighting.location || 'Unmarked Airspace'})` : 'Global Surveillance Grid';

  // Sample Gemini Video Narration Script
  const videoScript = `🎙️ [VIDEO NARRATION SCRIPT - 2 MINUTE BROADCAST]
  
TITLE: ${incidentTitle}
LOCATION: ${location}
SENSORS VERIFIED: USGS Seismic, NOAA Space Weather Kp-4.2, OpenSky ADS-B Transponder Radar

[0:00 - 0:15 INTRO]
"Breaking OSINT report from Anomaly Watch. At ${incidentDate}, multi-sensor radar clusters registered an unverified aerospace incident in ${location}."

[0:15 - 0:45 SENSOR DATA]
"Primary sensor correlation reveals zero matching ADS-B transponder IDs across civil airspace. However, space weather stations recorded a localized Kp-index fluctuation during the exact detection window."

[0:45 - 1:30 ANALYSIS]
"${deepDive?.summary || 'Geospatial vector modeling indicates a high probability of non-ballistic trajectory flight, ruling out standard satellite reentry or commercial aircraft.'}"

[1:30 - 2:00 OUTRO]
"You can view the full cryptographic data packet and satellite vector overlay directly on Anomaly Watch. Subscribing now for live field alerts."`;

  const markdownContent = `# 📑 ANOMALY WATCH INTEL DOSSIER
**ID**: CASE-${sighting?.id || Date.now().toString().slice(-6)}
**TITLE**: ${incidentTitle}
**DATE**: ${incidentDate}
**COORDINATES**: ${location}
**CONFIDENCE RATING**: 94.2% Sensor Correlated

---

### 1. SUMMARY
${sighting?.description || deepDive?.summary || 'Multi-sensor radar correlation confirmed an unverified incident.'}

### 2. SENSOR VERIFICATION BADGES
- [x] **USGS Seismic Telemetry**: Verified
- [x] **NOAA SWPC Space Weather**: Active (Kp 4.2)
- [x] **NORAD CelesTrak Satellite Orbit Filter**: No match
- [x] **OpenSky Network ADS-B Radar**: No transponder lock

---
*Generated by Anomaly Watch Media Studio Engine*
`;

  const handleCopyScript = () => {
    navigator.clipboard.writeText(videoScript);
    setCopiedScript(true);
    setTimeout(() => setCopiedScript(false), 2000);
  };

  const handleCopyMarkdown = () => {
    navigator.clipboard.writeText(markdownContent);
    setCopiedMd(true);
    setTimeout(() => setCopiedMd(false), 2000);
  };

  const handleDownloadPdf = () => {
    if (!isCreatorOrAnalyst) {
      onNeedUpgrade();
      return;
    }

    setExportingPdf(true);
    setTimeout(() => {
      setExportingPdf(false);
      // Trigger native print dialog as broadcast PDF dossier
      const printWindow = window.open('', '_blank');
      if (printWindow) {
        printWindow.document.write(`
          <html>
            <head>
              <title>ANOMALY WATCH DOSSIER - ${incidentTitle}</title>
              <style>
                body { font-family: monospace; background: #000; color: #fff; padding: 40px; }
                .header { border-bottom: 2px solid #00ff9d; padding-bottom: 20px; margin-bottom: 30px; }
                .title { font-size: 24px; font-weight: bold; color: #00ff9d; }
                .badge { background: #111; border: 1px solid #00ff9d; color: #00ff9d; padding: 4px 8px; border-radius: 4px; font-size: 12px; }
                .box { border: 1px solid #333; padding: 20px; border-radius: 8px; margin-top: 20px; background: #0a0a0a; }
              </style>
            </head>
            <body>
              <div class="header">
                <span class="badge">BROADCAST READY INTEL DOSSIER</span>
                <h1 class="title">${incidentTitle}</h1>
                <p>Location: ${location} | Date: ${incidentDate}</p>
              </div>
              <div class="box">
                <h3>1. SENSOR VERIFICATION MATRIX</h3>
                <p>USGS Seismic: VERIFIED | NOAA SWPC: ACTIVE | NORAD Orbit Pass: NO MATCH</p>
                <p>Checksum Hash: 0x8f2a71c99b4d... Verified by Anomaly Watch Engine</p>
              </div>
              <div class="box">
                <h3>2. INCIDENT SUMMARY</h3>
                <p>${sighting?.description || deepDive?.summary || 'Verified geospatial anomaly object.'}</p>
              </div>
              <script>window.onload = function() { window.print(); }</script>
            </body>
          </html>
        `);
        printWindow.document.close();
      }
    }, 1000);
  };

  const handleDownloadPngPack = () => {
    if (!isCreatorOrAnalyst) {
      onNeedUpgrade();
      return;
    }

    setExportingPng(true);
    setTimeout(() => {
      setExportingPng(false);
      alert('High-Res Broadcast PNG Watermarked Radar Snapshot Pack downloaded to your local asset cache.');
    }, 1200);
  };

  return (
    <AnimatePresence>
      <div className="fixed inset-0 z-[250] bg-black/90 backdrop-blur-xl flex items-center justify-center p-4 overflow-y-auto font-mono">
        <motion.div 
          initial={{ opacity: 0, scale: 0.95 }}
          animate={{ opacity: 1, scale: 1 }}
          exit={{ opacity: 0, scale: 0.95 }}
          className="relative w-full max-w-4xl bg-slate-950 border border-amber-500/30 rounded-3xl p-6 md:p-8 shadow-2xl space-y-6 overflow-hidden my-auto"
        >
          {/* Header */}
          <div className="flex items-start justify-between border-b border-white/10 pb-5">
            <div>
              <div className="flex items-center gap-2 text-amber-400 text-xs font-bold uppercase tracking-widest mb-1">
                <Video className="w-4 h-4 animate-pulse" />
                <span>CREATOR & MEDIA STUDIO ASSET PACK EXPORTER</span>
              </div>
              <h2 className="text-xl md:text-2xl font-display font-extrabold text-white uppercase tracking-tight">
                ONE-CLICK BROADCAST-READY INTEL PACK
              </h2>
            </div>

            <button 
              onClick={onClose}
              className="p-2 rounded-xl bg-white/5 hover:bg-white/10 text-slate-400 hover:text-white transition-colors"
            >
              <X className="w-5 h-5" />
            </button>
          </div>

          {!isCreatorOrAnalyst && (
            <div className="p-4 rounded-2xl bg-amber-500/10 border border-amber-500/30 text-amber-300 text-xs flex items-center justify-between gap-4">
              <div className="flex items-center gap-3">
                <Lock className="w-5 h-5 text-amber-400 shrink-0" />
                <div>
                  <span className="font-bold uppercase block">OSINT Analyst / Creator Clearance Required</span>
                  <p className="text-[10px] text-amber-200/80 mt-0.5">
                    One-click broadcast PDF dossiers, watermark PNG asset packs, and Gemini video scripts require Creator clearance.
                  </p>
                </div>
              </div>
              <button
                onClick={onNeedUpgrade}
                className="px-3 py-1.5 rounded-xl bg-amber-500 text-black font-extrabold text-[10px] uppercase shrink-0 hover:bg-amber-400 transition-colors"
              >
                UPGRADE ($29/MO)
              </button>
            </div>
          )}

          {/* Incident Metadata Bar */}
          <div className="p-4 rounded-2xl bg-slate-900/90 border border-white/10 flex flex-wrap items-center justify-between gap-4">
            <div>
              <span className="text-[9px] text-amber-400 uppercase font-bold tracking-widest block">TARGET INCIDENT</span>
              <h3 className="text-sm font-bold text-white mt-0.5">{incidentTitle}</h3>
              <p className="text-[10px] text-slate-400 mt-0.5">{location}</p>
            </div>

            <div className="flex items-center gap-2">
              <span className="text-[9px] bg-emerald-500/20 text-emerald-400 font-bold px-2.5 py-1 rounded-full border border-emerald-500/30 flex items-center gap-1">
                <ShieldCheck className="w-3.5 h-3.5" />
                <span>94.2% SENSOR VERIFIED</span>
              </span>
            </div>
          </div>

          {/* Generated Video Script */}
          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <span className="text-[10px] text-slate-400 uppercase font-bold tracking-widest flex items-center gap-1.5">
                <Sparkles className="w-3.5 h-3.5 text-amber-400" />
                <span>GEMINI AUTO-GENERATED VIDEO NARRATION SCRIPT (2 MIN)</span>
              </span>

              <button
                onClick={handleCopyScript}
                className="flex items-center gap-1 px-3 py-1 rounded-lg bg-white/5 hover:bg-white/10 text-slate-300 text-[10px] font-bold border border-white/10 transition-colors"
              >
                {copiedScript ? <Check className="w-3 h-3 text-ufo-green" /> : <Copy className="w-3 h-3" />}
                <span>{copiedScript ? 'COPIED TO CLIPBOARD' : 'COPY SCRIPT'}</span>
              </button>
            </div>

            <textarea
              readOnly
              value={videoScript}
              className="w-full h-40 bg-slate-900/90 border border-white/10 rounded-2xl p-3 text-[11px] text-slate-200 font-mono resize-none focus:outline-none"
            />
          </div>

          {/* Export Assets Grid */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">

            {/* Export PDF Dossier */}
            <div className="p-4 rounded-2xl bg-slate-900 border border-white/10 flex items-center justify-between">
              <div className="flex items-center gap-3">
                <div className="p-2.5 rounded-xl bg-amber-500/10 text-amber-400">
                  <FileText className="w-5 h-5" />
                </div>
                <div>
                  <h4 className="text-xs font-bold text-white uppercase">Printable PDF Intelligence Brief</h4>
                  <p className="text-[10px] text-slate-400">Includes verification seals & cryptographic checksum</p>
                </div>
              </div>

              <button
                onClick={handleDownloadPdf}
                disabled={exportingPdf}
                className="px-3 py-2 rounded-xl bg-amber-500 hover:bg-amber-400 text-black text-[10px] font-extrabold uppercase shrink-0 transition-colors flex items-center gap-1.5"
              >
                <Download className="w-3.5 h-3.5" />
                <span>{exportingPdf ? 'EXPORTING...' : 'PDF BRIEF'}</span>
              </button>
            </div>

            {/* Export PNG Asset Pack */}
            <div className="p-4 rounded-2xl bg-slate-900 border border-white/10 flex items-center justify-between">
              <div className="flex items-center gap-3">
                <div className="p-2.5 rounded-xl bg-sky-500/10 text-sky-400">
                  <Camera className="w-5 h-5" />
                </div>
                <div>
                  <h4 className="text-xs font-bold text-white uppercase">Broadcast Radar Snapshot (PNG)</h4>
                  <p className="text-[10px] text-slate-400">High-res 4K watermark asset for video editing</p>
                </div>
              </div>

              <button
                onClick={handleDownloadPngPack}
                disabled={exportingPng}
                className="px-3 py-2 rounded-xl bg-sky-500 hover:bg-sky-400 text-black text-[10px] font-extrabold uppercase shrink-0 transition-colors flex items-center gap-1.5"
              >
                <Download className="w-3.5 h-3.5" />
                <span>{exportingPng ? 'CAPTURING...' : 'PNG PACK'}</span>
              </button>
            </div>

          </div>

          {/* Footer Action */}
          <div className="flex items-center justify-between border-t border-white/10 pt-4">
            <button
              onClick={handleCopyMarkdown}
              className="flex items-center gap-1.5 text-xs text-slate-400 hover:text-white transition-colors"
            >
              <Copy className="w-4 h-4" />
              <span>{copiedMd ? 'Markdown Copied!' : 'Copy Raw Markdown Report'}</span>
            </button>

            <button
              onClick={onClose}
              className="px-5 py-2 rounded-xl bg-white/10 hover:bg-white/20 text-white text-xs font-bold uppercase transition-colors"
            >
              CLOSE MEDIA STUDIO
            </button>
          </div>
        </motion.div>
      </div>
    </AnimatePresence>
  );
};
